# Generated by Django 3.0.2 on 2020-01-31 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.CharField(choices=[('A FAVOR', 'A favor'), ('EN CONTRAR', 'En contra'), ('NO OPINA', 'No opina'), ('IMPRECISO', 'Impreciso')], max_length=20)),
                ('tittle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.Candidate')),
                ('key_topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opinions.KeyTopic')),
                ('tags', models.ManyToManyField(to='opinions.Tags')),
            ],
        ),
    ]
