# Generated by Django 3.0.2 on 2020-01-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='opinion',
            old_name='tags',
            new_name='tag',
        ),
    ]
