# Generated by Django 3.0.2 on 2020-01-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalcoalition',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='politicalcoalition',
            name='nickname',
            field=models.CharField(max_length=50),
        ),
    ]
