# Generated by Django 3.0.2 on 2020-01-31 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opinions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField()),
                ('snapshot', models.URLField(blank=True, null=True)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opinions.Opinion')),
            ],
        ),
    ]
