# Generated by Django 3.0.2 on 2020-01-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0002_auto_20200131_1506'),
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyTopic',
            new_name='Backup',
        ),
    ]
